language: perl
sudo: false

install:
  - perlbrew list
  - cpanm -n App::af
  - ./maint/ci-install-cmake
  - af missing | cpanm -n
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"
  - "5.28"

before_script:
  - export PATH="$HOME/opt/cmake3/bin:$PATH"

script:
  - dzil test -v

env:
  global:
    - PERL_USE_UNSAFE_INC=0
  matrix:
    - ALIEN_INSTALL_TYPE=system
    - ALIEN_INSTALL_TYPE=share
    - ALIEN_CMAKE_FROM_SOURCE=1
